-- ============================================================
-- OPENWITNESS
-- ============================================================
-- FROZEN PRODUCTION DATABASE BASELINE
--
-- Project:
--   OpenWitness
--
-- Version:
--   1.0.0
--
-- Schema:
--   V1
--
-- Migration:
--   create_openwitness_v1
--
-- Migration File:
--   20260825192716_create_openwitness_v1.sql
--
-- Developer / Maintainer:
--   Faruk Islam
--
-- GitHub:
--   https://github.com/farukislamyt/openwitness
--
-- Repository:
--   farukislamyt/openwitness
--
-- Application:
--   Next.js
--
-- Database:
--   Supabase PostgreSQL
--
-- Country:
--   Bangladesh
--
-- Primary Language:
--   Bengali / বাংলা
--
-- Public Authentication:
--   None
--
-- Staff Authentication:
--   Supabase Auth
--
-- Staff Roles:
--   admin
--   moderator
--
-- Reporter Identity:
--   NEVER STORED
--
-- Status:
--   FROZEN
--
-- ============================================================
--
-- IMPORTANT
--
-- This migration is the canonical OpenWitness V1 database
-- baseline.
--
-- AFTER THIS MIGRATION IS DEPLOYED:
--
--   DO NOT EDIT THIS FILE.
--   DO NOT RENAME THIS FILE.
--   DO NOT DELETE THIS FILE.
--
-- All future database changes MUST use a NEW migration.
--
-- ============================================================


begin;


-- ============================================================
-- 1. EXTENSIONS
-- ============================================================

create extension if not exists pgcrypto;


-- ============================================================
-- 2. PRIVATE SCHEMA
-- ============================================================
--
-- SECURITY DEFINER functions live here.
-- This schema must never be exposed through the Data API.
--
-- ============================================================

create schema if not exists private;

revoke all
on schema private
from public;

revoke all
on schema private
from anon;

revoke all
on schema private
from authenticated;


-- ============================================================
-- 3. ENUM TYPES
-- ============================================================

create type public.admin_role as enum (
  'admin',
  'moderator'
);


create type public.incident_status as enum (
  'pending',
  'under_review',
  'needs_revision',
  'approved',
  'rejected',
  'archived'
);


create type public.verification_status as enum (
  'reported',
  'verified',
  'disputed'
);


create type public.moderation_action_type as enum (
  'started_review',
  'approved',
  'rejected',
  'needs_revision',
  'archived',
  'edited',
  'redacted',
  'restored'
);


create type public.incident_report_reason as enum (
  'personal_information',
  'false_or_misleading',
  'harassment_or_hate',
  'threat_or_violence',
  'duplicate',
  'other'
);


create type public.incident_report_status as enum (
  'pending',
  'reviewed',
  'dismissed',
  'action_taken'
);


-- ============================================================
-- 4. GENERIC UPDATED_AT FUNCTION
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin

  new.updated_at = now();

  return new;

end;
$$;


revoke all
on function public.set_updated_at()
from public;

revoke all
on function public.set_updated_at()
from anon;

revoke all
on function public.set_updated_at()
from authenticated;


-- ============================================================
-- 5. CATEGORIES
-- ============================================================

create table public.categories (

  id uuid
    primary key
    default gen_random_uuid(),

  name text
    not null
    unique,

  slug text
    not null
    unique,

  description text,

  is_active boolean
    not null
    default true,

  sort_order integer
    not null
    default 0,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint categories_name_length
    check (
      char_length(trim(name))
      between 2 and 100
    ),

  constraint categories_slug_format
    check (
      slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),

  constraint categories_sort_order_nonnegative
    check (
      sort_order >= 0
    )
);


create index categories_active_sort_idx
on public.categories (
  is_active,
  sort_order
);


create trigger categories_set_updated_at
before update
on public.categories
for each row
execute function public.set_updated_at();


-- ============================================================
-- 6. BANGLADESH DIVISIONS
-- ============================================================

create table public.divisions (

  id smallint
    generated by default as identity
    primary key,

  name text
    not null
    unique,

  slug text
    not null
    unique,

  sort_order smallint
    not null
    unique,

  created_at timestamptz
    not null
    default now(),

  constraint divisions_name_length
    check (
      char_length(trim(name))
      between 2 and 100
    ),

  constraint divisions_slug_format
    check (
      slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),

  constraint divisions_sort_order_positive
    check (
      sort_order > 0
    )
);


-- ============================================================
-- 7. BANGLADESH DISTRICTS
-- ============================================================

create table public.districts (

  id smallint
    generated by default as identity
    primary key,

  division_id smallint
    not null
    references public.divisions(id)
    on update cascade
    on delete restrict,

  name text
    not null,

  slug text
    not null
    unique,

  sort_order smallint
    not null,

  created_at timestamptz
    not null
    default now(),

  unique (
    division_id,
    name
  ),

  unique (
    division_id,
    sort_order
  ),

  constraint districts_name_length
    check (
      char_length(trim(name))
      between 2 and 100
    ),

  constraint districts_slug_format
    check (
      slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    ),

  constraint districts_sort_order_positive
    check (
      sort_order > 0
    )
);


create index districts_division_fk_idx
on public.districts (
  division_id
);


-- ============================================================
-- 8. ADMIN / MODERATOR USERS
-- ============================================================
--
-- This table maps Supabase Auth users to application staff.
--
-- Public reporters NEVER enter this table.
--
-- The FIRST ADMIN is intentionally NOT created by this
-- migration.
--
-- Bootstrap procedure:
--
-- 1. Supabase Dashboard
--      Authentication
--        Users
--          Add user
--
-- 2. Copy the Auth user's UUID.
--
-- 3. Run from the Supabase SQL Editor:
--
-- insert into public.admin_users (
--   auth_user_id,
--   display_name,
--   role,
--   is_active
-- )
-- values (
--   'AUTH-USER-UUID',
--   'Faruk Islam',
--   'admin',
--   true
-- );
--
-- ============================================================

create table public.admin_users (

  id uuid
    primary key
    default gen_random_uuid(),

  auth_user_id uuid
    not null
    unique
    references auth.users(id)
    on update cascade
    on delete cascade,

  display_name text
    not null,

  role public.admin_role
    not null
    default 'moderator',

  is_active boolean
    not null
    default true,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint admin_users_display_name_length
    check (
      char_length(trim(display_name))
      between 2 and 100
    )
);


create index admin_users_role_active_idx
on public.admin_users (
  role,
  is_active
);


create trigger admin_users_set_updated_at
before update
on public.admin_users
for each row
execute function public.set_updated_at();


-- ============================================================
-- 9. INCIDENT PUBLIC NUMBER SEQUENCE
-- ============================================================
--
-- Generates:
--
--   OW-2026-000001
--   OW-2026-000002
--   ...
--
-- Direct sequence access is NOT granted to clients.
--
-- ============================================================

create sequence public.incident_public_number_seq;


-- ============================================================
-- 10. INCIDENTS
-- ============================================================
--
-- IMPORTANT PRIVACY RULE:
--
-- There is intentionally NO reporter identity.
--
-- NEVER add:
--
--   reporter_id
--   user_id
--   name
--   email
--   phone
--   ip_address
--   device_id
--   gps
--   tracking_id
--
-- ============================================================

create table public.incidents (

  id uuid
    primary key
    default gen_random_uuid(),

  public_id text
    not null
    unique,

  category_id uuid
    not null
    references public.categories(id)
    on update cascade
    on delete restrict,

  division_id smallint
    not null
    references public.divisions(id)
    on update cascade
    on delete restrict,

  district_id smallint
    not null
    references public.districts(id)
    on update cascade
    on delete restrict,

  title text
    not null,

  description text
    not null,

  incident_date date
    not null,

  status public.incident_status
    not null
    default 'pending',

  verification_status public.verification_status
    not null
    default 'reported',

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  published_at timestamptz,

  constraint incidents_title_length
    check (
      char_length(trim(title))
      between 5 and 200
    ),

  constraint incidents_description_length
    check (
      char_length(trim(description))
      between 20 and 10000
    ),

  constraint incidents_publication_consistency
    check (
      (
        status = 'approved'
        and published_at is not null
      )
      or
      (
        status <> 'approved'
        and published_at is null
      )
    )
);


-- ============================================================
-- 11. INCIDENT FOREIGN KEY INDEXES
-- ============================================================

create index incidents_category_fk_idx
on public.incidents (
  category_id
);

create index incidents_division_fk_idx
on public.incidents (
  division_id
);

create index incidents_district_fk_idx
on public.incidents (
  district_id
);


-- ============================================================
-- 12. INCIDENT QUERY INDEXES
-- ============================================================

create index incidents_public_listing_idx
on public.incidents (
  published_at desc
)
where status = 'approved';


create index incidents_category_public_idx
on public.incidents (
  category_id,
  published_at desc
)
where status = 'approved';


create index incidents_division_public_idx
on public.incidents (
  division_id,
  published_at desc
)
where status = 'approved';


create index incidents_district_public_idx
on public.incidents (
  district_id,
  published_at desc
)
where status = 'approved';


create index incidents_moderation_queue_idx
on public.incidents (
  status,
  created_at desc
)
where status in (
  'pending',
  'under_review',
  'needs_revision'
);


create index incidents_verification_public_idx
on public.incidents (
  verification_status,
  published_at desc
)
where status = 'approved';


-- ============================================================
-- 13. INCIDENT UPDATED_AT TRIGGER
-- ============================================================

create trigger incidents_set_updated_at
before update
on public.incidents
for each row
execute function public.set_updated_at();


-- ============================================================
-- 14. INCIDENT LOCATION VALIDATION
-- ============================================================

create or replace function private.validate_incident_location()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  if not exists (
    select 1
    from public.districts d
    where d.id = new.district_id
      and d.division_id = new.division_id
  ) then

    raise exception
      'District does not belong to selected division';

  end if;

  return new;

end;
$$;


revoke all
on function private.validate_incident_location()
from public;

revoke all
on function private.validate_incident_location()
from anon;

revoke all
on function private.validate_incident_location()
from authenticated;


create trigger incidents_validate_location
before insert or update
on public.incidents
for each row
execute function private.validate_incident_location();


-- ============================================================
-- 15. INCIDENT DATE VALIDATION
-- ============================================================
--
-- CURRENT_DATE is intentionally NOT used inside a CHECK
-- constraint because it is not immutable.
--
-- Future dates are therefore validated by this trigger.
--
-- ============================================================

create or replace function private.validate_incident_date()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  if new.incident_date > current_date then

    raise exception
      'Incident date cannot be in the future';

  end if;

  return new;

end;
$$;


revoke all
on function private.validate_incident_date()
from public;

revoke all
on function private.validate_incident_date()
from anon;

revoke all
on function private.validate_incident_date()
from authenticated;


create trigger incidents_validate_date
before insert or update
on public.incidents
for each row
execute function private.validate_incident_date();


-- ============================================================
-- 16. INCIDENT PUBLIC ID GENERATOR
-- ============================================================

create or replace function private.generate_incident_public_id()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  new.public_id :=
    'OW-' ||
    to_char(current_date, 'YYYY') ||
    '-' ||
    lpad(
      nextval(
        'public.incident_public_number_seq'
      )::text,
      6,
      '0'
    );

  return new;

end;
$$;


revoke all
on function private.generate_incident_public_id()
from public;

revoke all
on function private.generate_incident_public_id()
from anon;

revoke all
on function private.generate_incident_public_id()
from authenticated;


create trigger incidents_generate_public_id
before insert
on public.incidents
for each row
execute function private.generate_incident_public_id();


-- ============================================================
-- 17. INCIDENT SYSTEM FIELD PROTECTION
-- ============================================================
--
-- Prevent modification of:
--
--   id
--   public_id
--   created_at
--
-- ============================================================

create or replace function private.protect_incident_system_fields()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin

  new.id := old.id;

  new.public_id := old.public_id;

  new.created_at := old.created_at;

  return new;

end;
$$;


revoke all
on function private.protect_incident_system_fields()
from public;

revoke all
on function private.protect_incident_system_fields()
from anon;

revoke all
on function private.protect_incident_system_fields()
from authenticated;


create trigger incidents_protect_system_fields
before update
on public.incidents
for each row
execute function private.protect_incident_system_fields();


-- ============================================================
-- 18. MODERATION ACTIONS
-- ============================================================

create table public.moderation_actions (

  id uuid
    primary key
    default gen_random_uuid(),

  incident_id uuid
    not null
    references public.incidents(id)
    on update cascade
    on delete cascade,

  admin_user_id uuid
    not null
    references public.admin_users(id)
    on update cascade
    on delete restrict,

  action public.moderation_action_type
    not null,

  notes text,

  created_at timestamptz
    not null
    default now(),

  constraint moderation_actions_notes_length
    check (
      notes is null
      or char_length(notes) <= 5000
    )
);


create index moderation_actions_incident_fk_idx
on public.moderation_actions (
  incident_id
);

create index moderation_actions_admin_fk_idx
on public.moderation_actions (
  admin_user_id
);

create index moderation_actions_incident_time_idx
on public.moderation_actions (
  incident_id,
  created_at desc
);

create index moderation_actions_admin_time_idx
on public.moderation_actions (
  admin_user_id,
  created_at desc
);


-- ============================================================
-- 19. PUBLIC INCIDENT FLAGS
-- ============================================================

create table public.incident_reports (

  id uuid
    primary key
    default gen_random_uuid(),

  incident_id uuid
    not null
    references public.incidents(id)
    on update cascade
    on delete cascade,

  reason public.incident_report_reason
    not null,

  description text,

  status public.incident_report_status
    not null
    default 'pending',

  reviewed_by uuid
    references public.admin_users(id)
    on update cascade
    on delete set null,

  reviewed_at timestamptz,

  created_at timestamptz
    not null
    default now(),

  constraint incident_reports_description_length
    check (
      description is null
      or char_length(trim(description)) <= 3000
    ),

  constraint incident_reports_review_consistency
    check (
      (
        status = 'pending'
        and reviewed_by is null
        and reviewed_at is null
      )
      or
      (
        status <> 'pending'
        and reviewed_by is not null
        and reviewed_at is not null
      )
    )
);


create index incident_reports_incident_fk_idx
on public.incident_reports (
  incident_id
);

create index incident_reports_reviewed_by_fk_idx
on public.incident_reports (
  reviewed_by
);

create index incident_reports_pending_idx
on public.incident_reports (
  created_at desc
)
where status = 'pending';

create index incident_reports_incident_time_idx
on public.incident_reports (
  incident_id,
  created_at desc
);


-- ============================================================
-- 20. STAFF SECURITY FUNCTIONS
-- ============================================================

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.auth_user_id = (select auth.uid())
      and au.is_active = true
  );
$$;


create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.auth_user_id = (select auth.uid())
      and au.is_active = true
      and au.role = 'admin'
  );
$$;


create or replace function private.current_staff_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select au.id
  from public.admin_users au
  where au.auth_user_id = (select auth.uid())
    and au.is_active = true
  limit 1;
$$;


revoke all
on function private.is_staff()
from public, anon, authenticated;

revoke all
on function private.is_admin()
from public, anon, authenticated;

revoke all
on function private.current_staff_id()
from public, anon, authenticated;


grant execute
on function private.is_staff()
to authenticated;

grant execute
on function private.is_admin()
to authenticated;

grant execute
on function private.current_staff_id()
to authenticated;


-- ============================================================
-- 21. AUTOMATIC MODERATION AUDIT
-- ============================================================
--
-- Status changes are automatically recorded.
--
-- Content changes are automatically recorded as "edited".
--
-- This prevents a moderator from changing an incident status
-- without creating an audit trail.
--
-- ============================================================

create or replace function private.audit_incident_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare

  staff_id uuid;

  audit_action public.moderation_action_type;

begin

  staff_id := private.current_staff_id();

  -- No authenticated staff identity:
  -- do not create an application-level audit record.
  --
  -- This can occur during migrations or trusted database
  -- administration.

  if staff_id is null then
    return new;
  end if;


  -- Status transition audit.

  if new.status is distinct from old.status then

    audit_action :=
      case new.status
        when 'under_review'
          then 'started_review'::public.moderation_action_type

        when 'approved'
          then 'approved'::public.moderation_action_type

        when 'rejected'
          then 'rejected'::public.moderation_action_type

        when 'needs_revision'
          then 'needs_revision'::public.moderation_action_type

        when 'archived'
          then 'archived'::public.moderation_action_type

        else
          null
      end;


    if audit_action is not null then

      insert into public.moderation_actions (
        incident_id,
        admin_user_id,
        action,
        notes
      )
      values (
        new.id,
        staff_id,
        audit_action,
        null
      );

    end if;

  end if;


  -- Content/location/category/date modification audit.

  if
    new.title is distinct from old.title
    or new.description is distinct from old.description
    or new.category_id is distinct from old.category_id
    or new.division_id is distinct from old.division_id
    or new.district_id is distinct from old.district_id
    or new.incident_date is distinct from old.incident_date
    or new.verification_status is distinct from old.verification_status
  then

    insert into public.moderation_actions (
      incident_id,
      admin_user_id,
      action,
      notes
    )
    values (
      new.id,
      staff_id,
      'edited'::public.moderation_action_type,
      null
    );

  end if;


  return new;

end;
$$;


revoke all
on function private.audit_incident_change()
from public;

revoke all
on function private.audit_incident_change()
from anon;

revoke all
on function private.audit_incident_change()
from authenticated;


create trigger incidents_audit_changes
after update
on public.incidents
for each row
execute function private.audit_incident_change();


-- ============================================================
-- 22. DATABASE METADATA
-- ============================================================
--
-- This table contains project/schema metadata only.
--
-- It is NOT application data.
--
-- It is intentionally not exposed to anonymous users.
--
-- Metadata is immutable from the application API.
--
-- ============================================================

create table public.database_metadata (

  key text
    primary key,

  value text
    not null,

  created_at timestamptz
    not null
    default now(),

  constraint database_metadata_key_length
    check (
      char_length(trim(key))
      between 1 and 100
    ),

  constraint database_metadata_value_length
    check (
      char_length(value)
      between 1 and 2000
    )
);


insert into public.database_metadata (
  key,
  value
)
values

(
  'project_name',
  'OpenWitness'
),

(
  'project_version',
  '1.0.0'
),

(
  'database_version',
  '1'
),

(
  'schema_status',
  'FROZEN'
),

(
  'migration_name',
  'create_openwitness_v1'
),

(
  'migration_file',
  '20260825192716_create_openwitness_v1.sql'
),

(
  'developer',
  'Faruk Islam'
),

(
  'github_owner',
  'farukislamyt'
),

(
  'github_repository',
  'openwitness'
),

(
  'github_url',
  'https://github.com/farukislamyt/openwitness'
),

(
  'application',
  'Next.js'
),

(
  'database',
  'Supabase PostgreSQL'
),

(
  'country',
  'Bangladesh'
),

(
  'primary_language',
  'বাংলা'
),

(
  'public_authentication',
  'none'
),

(
  'staff_authentication',
  'Supabase Auth'
),

(
  'staff_roles',
  'admin, moderator'
),

(
  'reporter_identity_storage',
  'none'
),

(
  'privacy_model',
  'Anonymous public-interest reporting'
),

(
  'created_date',
  '2026-08-25'
),

(
  'schema_policy',
  'Frozen V1 baseline; future changes require new migrations'
);


-- ============================================================
-- 23. RLS ENABLEMENT
-- ============================================================

alter table public.categories
enable row level security;

alter table public.divisions
enable row level security;

alter table public.districts
enable row level security;

alter table public.admin_users
enable row level security;

alter table public.incidents
enable row level security;

alter table public.moderation_actions
enable row level security;

alter table public.incident_reports
enable row level security;

alter table public.database_metadata
enable row level security;


-- ============================================================
-- 24. FORCE RLS
-- ============================================================

alter table public.categories
force row level security;

alter table public.divisions
force row level security;

alter table public.districts
force row level security;

alter table public.admin_users
force row level security;

alter table public.incidents
force row level security;

alter table public.moderation_actions
force row level security;

alter table public.incident_reports
force row level security;

alter table public.database_metadata
force row level security;


-- ============================================================
-- 25. REVOKE DEFAULT CLIENT ACCESS
-- ============================================================

revoke all
on table public.categories
from anon, authenticated;

revoke all
on table public.divisions
from anon, authenticated;

revoke all
on table public.districts
from anon, authenticated;

revoke all
on table public.admin_users
from anon, authenticated;

revoke all
on table public.incidents
from anon, authenticated;

revoke all
on table public.moderation_actions
from anon, authenticated;

revoke all
on table public.incident_reports
from anon, authenticated;

revoke all
on table public.database_metadata
from anon, authenticated;


-- ============================================================
-- 26. PUBLIC READ GRANTS
-- ============================================================

grant select
on public.categories
to anon, authenticated;

grant select
on public.divisions
to anon, authenticated;

grant select
on public.districts
to anon, authenticated;


-- ============================================================
-- 27. PUBLIC WRITE GRANTS
-- ============================================================

grant insert
on public.incidents
to anon, authenticated;

grant insert
on public.incident_reports
to anon, authenticated;


-- ============================================================
-- 28. STAFF GRANTS
-- ============================================================

grant select, update
on public.incidents
to authenticated;

grant select, insert
on public.moderation_actions
to authenticated;

grant select, update
on public.incident_reports
to authenticated;

grant select
on public.admin_users
to authenticated;


-- ============================================================
-- 29. ADMIN GRANTS
-- ============================================================

grant insert, update, delete
on public.categories
to authenticated;

grant insert, update, delete
on public.divisions
to authenticated;

grant insert, update, delete
on public.districts
to authenticated;

grant insert, update, delete
on public.admin_users
to authenticated;

grant delete
on public.incidents
to authenticated;

grant update, delete
on public.moderation_actions
to authenticated;


-- ============================================================
-- 30. CATEGORIES RLS
-- ============================================================

create policy categories_select
on public.categories
for select
to anon, authenticated
using (
  is_active = true
  or
  (select private.is_admin())
);


create policy categories_admin_insert
on public.categories
for insert
to authenticated
with check (
  (select private.is_admin())
);


create policy categories_admin_update
on public.categories
for update
to authenticated
using (
  (select private.is_admin())
)
with check (
  (select private.is_admin())
);


create policy categories_admin_delete
on public.categories
for delete
to authenticated
using (
  (select private.is_admin())
);


-- ============================================================
-- 31. DIVISIONS RLS
-- ============================================================

create policy divisions_select
on public.divisions
for select
to anon, authenticated
using (
  true
);


create policy divisions_admin_insert
on public.divisions
for insert
to authenticated
with check (
  (select private.is_admin())
);


create policy divisions_admin_update
on public.divisions
for update
to authenticated
using (
  (select private.is_admin())
)
with check (
  (select private.is_admin())
);


create policy divisions_admin_delete
on public.divisions
for delete
to authenticated
using (
  (select private.is_admin())
);


-- ============================================================
-- 32. DISTRICTS RLS
-- ============================================================

create policy districts_select
on public.districts
for select
to anon, authenticated
using (
  true
);


create policy districts_admin_insert
on public.districts
for insert
to authenticated
with check (
  (select private.is_admin())
);


create policy districts_admin_update
on public.districts
for update
to authenticated
using (
  (select private.is_admin())
)
with check (
  (select private.is_admin())
);


create policy districts_admin_delete
on public.districts
for delete
to authenticated
using (
  (select private.is_admin())
);


-- ============================================================
-- 33. ADMIN USERS RLS
-- ============================================================

create policy admin_users_select
on public.admin_users
for select
to authenticated
using (
  auth_user_id = (select auth.uid())
  or
  (select private.is_admin())
);


create policy admin_users_admin_insert
on public.admin_users
for insert
to authenticated
with check (
  (select private.is_admin())
);


create policy admin_users_admin_update
on public.admin_users
for update
to authenticated
using (
  (select private.is_admin())
)
with check (
  (select private.is_admin())
);


create policy admin_users_admin_delete
on public.admin_users
for delete
to authenticated
using (
  (select private.is_admin())
);


-- ============================================================
-- 34. INCIDENTS RLS
-- ============================================================

create policy incidents_select
on public.incidents
for select
to anon, authenticated
using (
  status = 'approved'
  or
  (select private.is_staff())
);


create policy incidents_public_insert
on public.incidents
for insert
to anon, authenticated
with check (
  status = 'pending'
  and verification_status = 'reported'
  and published_at is null
);


create policy incidents_staff_update
on public.incidents
for update
to authenticated
using (
  (select private.is_staff())
)
with check (
  (select private.is_staff())
);


create policy incidents_admin_delete
on public.incidents
for delete
to authenticated
using (
  (select private.is_admin())
);


-- ============================================================
-- 35. MODERATION ACTIONS RLS
-- ============================================================

create policy moderation_actions_staff_select
on public.moderation_actions
for select
to authenticated
using (
  (select private.is_staff())
);


create policy moderation_actions_staff_insert
on public.moderation_actions
for insert
to authenticated
with check (
  (select private.is_staff())
  and admin_user_id = (
    select private.current_staff_id()
  )
);


create policy moderation_actions_admin_update
on public.moderation_actions
for update
to authenticated
using (
  (select private.is_admin())
)
with check (
  (select private.is_admin())
);


create policy moderation_actions_admin_delete
on public.moderation_actions
for delete
to authenticated
using (
  (select private.is_admin())
);


-- ============================================================
-- 36. INCIDENT REPORTS RLS
-- ============================================================

create policy incident_reports_public_insert
on public.incident_reports
for insert
to anon, authenticated
with check (

  status = 'pending'

  and reviewed_by is null

  and reviewed_at is null

  and exists (
    select 1
    from public.incidents i
    where i.id = incident_id
      and i.status = 'approved'
  )

);


create policy incident_reports_staff_select
on public.incident_reports
for select
to authenticated
using (
  (select private.is_staff())
);


create policy incident_reports_staff_update
on public.incident_reports
for update
to authenticated
using (
  (select private.is_staff())
)
with check (
  (select private.is_staff())
);


-- ============================================================
-- 37. DATABASE METADATA RLS
-- ============================================================

create policy database_metadata_admin_select
on public.database_metadata
for select
to authenticated
using (
  (select private.is_admin())
);


-- ============================================================
-- 38. PUBLIC INCIDENT VIEW
-- ============================================================
--
-- security_invoker ensures underlying RLS remains effective.
--
-- ============================================================

create or replace view public.public_incidents
with (
  security_invoker = true
)
as

select

  i.id,

  i.public_id,

  i.title,

  i.description,

  i.incident_date,

  i.verification_status,

  i.published_at,

  c.name as category,

  c.slug as category_slug,

  d.name as division,

  d.slug as division_slug,

  ds.name as district,

  ds.slug as district_slug

from public.incidents i

join public.categories c
  on c.id = i.category_id

join public.divisions d
  on d.id = i.division_id

join public.districts ds
  on ds.id = i.district_id

where i.status = 'approved';


revoke all
on public.public_incidents
from anon, authenticated;


grant select
on public.public_incidents
to anon, authenticated;


-- ============================================================
-- 39. SEQUENCE SECURITY
-- ============================================================

revoke all
on sequence public.incident_public_number_seq
from public, anon, authenticated;


-- ============================================================
-- 40. DEFAULT PRIVILEGES
-- ============================================================
--
-- Keep future objects private by default.
--
-- Explicit grants must be added for every future API object.
--
-- ============================================================

alter default privileges
revoke execute
on functions
from public;

alter default privileges
revoke execute
on functions
from anon;

alter default privileges
revoke execute
on functions
from authenticated;

alter default privileges
revoke all
on tables
from anon;

alter default privileges
revoke all
on tables
from authenticated;

alter default privileges
revoke all
on sequences
from anon;

alter default privileges
revoke all
on sequences
from authenticated;


-- ============================================================
-- 41. DATABASE / SCHEMA COMMENTS
-- ============================================================

comment on schema public is
'OpenWitness V1 production database schema. Anonymous public-interest reporting platform for Bangladesh.';

comment on table public.categories is
'OpenWitness V1 categories. Developer: Faruk Islam. Repository: github.com/farukislamyt/openwitness. Status: FROZEN.';

comment on table public.divisions is
'OpenWitness V1 — 8 administrative divisions of Bangladesh. Status: FROZEN.';

comment on table public.districts is
'OpenWitness V1 — 64 districts of Bangladesh mapped to divisions. Status: FROZEN.';

comment on table public.admin_users is
'OpenWitness V1 — authenticated admin and moderator directory. Status: FROZEN.';

comment on table public.incidents is
'OpenWitness V1 — anonymous public-interest incident reports. Reporter identity is never stored. Status: FROZEN.';

comment on table public.moderation_actions is
'OpenWitness V1 — private moderation audit trail. Status: FROZEN.';

comment on table public.incident_reports is
'OpenWitness V1 — anonymous public flags against approved incidents. Status: FROZEN.';

comment on table public.database_metadata is
'OpenWitness V1 — immutable project and database metadata. Status: FROZEN.';

comment on view public.public_incidents is
'OpenWitness V1 — public-safe view of approved incidents. Status: FROZEN.';


-- ============================================================
-- 42. SEED CATEGORIES
-- ============================================================

insert into public.categories (
  name,
  slug,
  description,
  sort_order
)
values

(
  'দুর্নীতি ও ঘুষ',
  'corruption-bribery',
  'দুর্নীতি, ঘুষ ও অনৈতিক সুবিধা সংক্রান্ত ঘটনা',
  1
),

(
  'প্রতারণা',
  'fraud',
  'প্রতারণা, জালিয়াতি ও প্রতারণামূলক কার্যক্রম',
  2
),

(
  'চাঁদাবাজি',
  'extortion',
  'চাঁদাবাজি বা জোরপূর্বক অর্থ বা সুবিধা আদায়',
  3
),

(
  'হয়রানি',
  'harassment',
  'হয়রানি ও অনাকাঙ্ক্ষিত আচরণ',
  4
),

(
  'সহিংসতা',
  'violence',
  'সহিংসতা ও জননিরাপত্তা-সম্পর্কিত ঘটনা',
  5
),

(
  'নির্যাতন ও শোষণ',
  'abuse-exploitation',
  'নির্যাতন, শোষণ ও জবরদস্তি',
  6
),

(
  'সাইবার অপরাধ',
  'cybercrime',
  'অনলাইন ও ডিজিটাল অপরাধ',
  7
),

(
  'সরকারি সেবায় অনিয়ম',
  'public-service-irregularity',
  'সরকারি সেবা ও প্রশাসনিক অনিয়ম',
  8
),

(
  'স্বাস্থ্যসেবা',
  'healthcare',
  'স্বাস্থ্যসেবা সংক্রান্ত জনস্বার্থের অভিযোগ',
  9
),

(
  'শিক্ষা',
  'education',
  'শিক্ষা প্রতিষ্ঠান ও শিক্ষা ব্যবস্থার অনিয়ম',
  10
),

(
  'পরিবেশ',
  'environment',
  'পরিবেশ দূষণ ও পরিবেশগত অনিয়ম',
  11
),

(
  'জননিরাপত্তা',
  'public-safety',
  'জননিরাপত্তা ও ঝুঁকি সংক্রান্ত ঘটনা',
  12
),

(
  'ভোক্তা অধিকার',
  'consumer-rights',
  'পণ্য ও সেবা সংক্রান্ত ভোক্তা অধিকার সমস্যা',
  13
),

(
  'ভূমি ও সম্পত্তি',
  'land-property',
  'ভূমি ও সম্পত্তি সংক্রান্ত জনস্বার্থের ঘটনা',
  14
),

(
  'কর্মক্ষেত্রের অনিয়ম',
  'workplace-irregularity',
  'কর্মক্ষেত্রের অনিয়ম ও অধিকার সংক্রান্ত ঘটনা',
  15
),

(
  'অন্যান্য জনস্বার্থের বিষয়',
  'other-public-interest',
  'অন্যান্য জনস্বার্থের ঘটনা',
  16
);


-- ============================================================
-- 43. SEED 8 BANGLADESH DIVISIONS
-- ============================================================

insert into public.divisions (
  id,
  name,
  slug,
  sort_order
)
values

(1, 'ঢাকা', 'dhaka', 1),
(2, 'চট্টগ্রাম', 'chattogram', 2),
(3, 'রাজশাহী', 'rajshahi', 3),
(4, 'খুলনা', 'khulna', 4),
(5, 'বরিশাল', 'barishal', 5),
(6, 'সিলেট', 'sylhet', 6),
(7, 'রংপুর', 'rangpur', 7),
(8, 'ময়মনসিংহ', 'mymensingh', 8);


select setval(
  pg_get_serial_sequence(
    'public.divisions',
    'id'
  ),
  8,
  true
);


-- ============================================================
-- 44. SEED 64 BANGLADESH DISTRICTS
-- ============================================================

insert into public.districts (
  division_id,
  name,
  slug,
  sort_order
)
values

-- ঢাকা
(1, 'ঢাকা', 'dhaka', 1),
(1, 'ফরিদপুর', 'faridpur', 2),
(1, 'গাজীপুর', 'gazipur', 3),
(1, 'গোপালগঞ্জ', 'gopalganj', 4),
(1, 'কিশোরগঞ্জ', 'kishoreganj', 5),
(1, 'মাদারীপুর', 'madaripur', 6),
(1, 'মানিকগঞ্জ', 'manikganj', 7),
(1, 'মুন্সিগঞ্জ', 'munshiganj', 8),
(1, 'নারায়ণগঞ্জ', 'narayanganj', 9),
(1, 'নরসিংদী', 'narsingdi', 10),
(1, 'রাজবাড়ী', 'rajbari', 11),
(1, 'শরীয়তপুর', 'shariatpur', 12),
(1, 'টাঙ্গাইল', 'tangail', 13),

-- চট্টগ্রাম
(2, 'বান্দরবান', 'bandarban', 1),
(2, 'ব্রাহ্মণবাড়িয়া', 'brahmanbaria', 2),
(2, 'চাঁদপুর', 'chandpur', 3),
(2, 'চট্টগ্রাম', 'chattogram', 4),
(2, 'কুমিল্লা', 'cumilla', 5),
(2, 'কক্সবাজার', 'coxsbazar', 6),
(2, 'ফেনী', 'feni', 7),
(2, 'খাগড়াছড়ি', 'khagrachhari', 8),
(2, 'লক্ষ্মীপুর', 'lakshmipur', 9),
(2, 'নোয়াখালী', 'noakhali', 10),
(2, 'রাঙ্গামাটি', 'rangamati', 11),

-- রাজশাহী
(3, 'বগুড়া', 'bogura', 1),
(3, 'জয়পুরহাট', 'joypurhat', 2),
(3, 'নওগাঁ', 'naogaon', 3),
(3, 'নাটোর', 'natore', 4),
(3, 'চাঁপাইনবাবগঞ্জ', 'chapainawabganj', 5),
(3, 'পাবনা', 'pabna', 6),
(3, 'রাজশাহী', 'rajshahi', 7),
(3, 'সিরাজগঞ্জ', 'sirajganj', 8),

-- খুলনা
(4, 'বাগেরহাট', 'bagerhat', 1),
(4, 'চুয়াডাঙ্গা', 'chuadanga', 2),
(4, 'যশোর', 'jashore', 3),
(4, 'ঝিনাইদহ', 'jhenaidah', 4),
(4, 'খুলনা', 'khulna', 5),
(4, 'কুষ্টিয়া', 'kushtia', 6),
(4, 'মাগুরা', 'magura', 7),
(4, 'মেহেরপুর', 'meherpur', 8),
(4, 'নড়াইল', 'narail', 9),
(4, 'সাতক্ষীরা', 'satkhira', 10),

-- বরিশাল
(5, 'বরগুনা', 'barguna', 1),
(5, 'বরিশাল', 'barishal', 2),
(5, 'ভোলা', 'bhola', 3),
(5, 'ঝালকাঠি', 'jhalokathi', 4),
(5, 'পটুয়াখালী', 'patuakhali', 5),
(5, 'পিরোজপুর', 'pirojpur', 6),

-- সিলেট
(6, 'হবিগঞ্জ', 'habiganj', 1),
(6, 'মৌলভীবাজার', 'moulvibazar', 2),
(6, 'সুনামগঞ্জ', 'sunamganj', 3),
(6, 'সিলেট', 'sylhet', 4),

-- রংপুর
(7, 'দিনাজপুর', 'dinajpur', 1),
(7, 'গাইবান্ধা', 'gaibandha', 2),
(7, 'কুড়িগ্রাম', 'kurigram', 3),
(7, 'লালমনিরহাট', 'lalmonirhat', 4),
(7, 'নীলফামারী', 'nilphamari', 5),
(7, 'পঞ্চগড়', 'panchagarh', 6),
(7, 'রংপুর', 'rangpur', 7),
(7, 'ঠাকুরগাঁও', 'thakurgaon', 8),

-- ময়মনসিংহ
(8, 'জামালপুর', 'jamalpur', 1),
(8, 'ময়মনসিংহ', 'mymensingh', 2),
(8, 'নেত্রকোনা', 'netrokona', 3),
(8, 'শেরপুর', 'sherpur', 4);


-- ============================================================
-- 45. FINAL METADATA COMMENTS
-- ============================================================

comment on table public.database_metadata is
'Immutable OpenWitness V1 project metadata. Developer: Faruk Islam. GitHub: github.com/farukislamyt/openwitness. Status: FROZEN.';


-- ============================================================
-- 46. COMMIT
-- ============================================================

commit;